version: '3'

services:

  postgreSQL:
    image: postgres:13-alpine
    ports:
      - "6666:5432"
    environment:
      - DEBUG=false
      - POSTGRES_USER=dev-user
      - POSTGRES_PASSWORD=dev-password
      - POSTGRES_DB=jwt_auth
    volumes:
      - post_db:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  post_db:

